name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - "[0-9]+.x"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-versions:
          - lowest
          - highest
          - locked
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - uses: ramsey/composer-install@v1
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
      - name: PHPUnit
        run: vendor/bin/phpunit
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-versions:
          - lowest
          - highest
          - locked
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - uses: ramsey/composer-install@v1
        with:
          dependency-versions: "${{ matrix.dependency-versions }}"
      - name: Psalm
        run: vendor/bin/psalm
